/**
 * Generate Featured Image - Supabase Edge Function
 *
 * This function generates featured images for blog posts using AI image generation.
 * Supports Stability AI and OpenAI DALL-E 3.
 *
 * HOW IT WORKS:
 * 1. Receives a prompt describing the desired image
 * 2. Generates image using Stability AI or DALL-E 3
 * 3. Returns the image URL (hosted by the AI service)
 * 4. Optionally uploads to Supabase Storage for long-term hosting
 *
 * STABILITY AI:
 * - Uses Stable Diffusion models
 * - Great for realistic and artistic images
 * - Docs: https://platform.stability.ai/docs/api-reference
 *
 * DALL-E 3:
 * - Uses OpenAI's DALL-E 3 model
 * - Great for creative and conceptual images
 * - Docs: https://platform.openai.com/docs/guides/images
 *
 * REQUEST BODY:
 * {
 *   "prompt": "A modern office workspace with laptop",
 *   "provider": "stability" | "dalle", // optional, defaults to stability
 *   "style": "photographic" | "digital-art" | "cinematic", // optional
 *   "aspect_ratio": "16:9" | "1:1" | "4:3" // optional, defaults to 16:9
 * }
 *
 * RESPONSE:
 * {
 *   "success": true,
 *   "image_url": "https://...",
 *   "provider": "stability",
 *   "prompt": "A modern office workspace..."
 * }
 */

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { getCorsHeaders, handleCorsPreflightRequest, jsonResponse, errorResponse } from '../_shared/cors.ts';

// Environment variables
const STABILITY_API_KEY = Deno.env.get('STABILITY_API_KEY');
const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY');

/**
 * Stability AI image generation
 */
async function generateWithStability(
  prompt: string,
  style: string = 'photographic',
  aspectRatio: string = '16:9'
): Promise<string> {
  console.log('Generating image with Stability AI...');

  if (!STABILITY_API_KEY) {
    throw new Error('STABILITY_API_KEY not configured');
  }

  // Stability AI SDXL 1.0 endpoint
  const apiUrl = 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image';

  // Convert aspect ratio to dimensions
  let width = 1024;
  let height = 1024;

  if (aspectRatio === '16:9') {
    width = 1344;
    height = 768;
  } else if (aspectRatio === '4:3') {
    width = 1152;
    height = 896;
  }

  // Prepare request body
  const requestBody = {
    text_prompts: [
      {
        text: prompt,
        weight: 1,
      },
    ],
    cfg_scale: 7, // How strictly to follow the prompt
    height: height,
    width: width,
    steps: 30, // Number of diffusion steps
    samples: 1, // Number of images to generate
    style_preset: style, // photographic, digital-art, cinematic, etc.
  };

  console.log('Stability AI request:', { width, height, style });

  const response = await fetch(apiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${STABILITY_API_KEY}`,
      'Accept': 'application/json',
    },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const error = await response.json();
    console.error('Stability AI error:', error);
    throw new Error(`Stability AI failed: ${error.message || response.status}`);
  }

  const result = await response.json();

  // Extract base64 image and convert to data URL
  if (!result.artifacts || result.artifacts.length === 0) {
    throw new Error('No image generated by Stability AI');
  }

  const base64Image = result.artifacts[0].base64;
  const imageUrl = `data:image/png;base64,${base64Image}`;

  console.log('Image generated successfully with Stability AI');

  return imageUrl;
}

/**
 * OpenAI DALL-E 3 image generation
 */
async function generateWithDalle(
  prompt: string,
  aspectRatio: string = '16:9'
): Promise<string> {
  console.log('Generating image with DALL-E 3...');

  if (!OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY not configured');
  }

  // DALL-E 3 supports specific sizes
  let size: '1024x1024' | '1792x1024' | '1024x1792';

  if (aspectRatio === '16:9') {
    size = '1792x1024'; // Landscape
  } else if (aspectRatio === '1:1') {
    size = '1024x1024'; // Square
  } else {
    size = '1024x1792'; // Portrait (close to 4:3)
  }

  console.log('DALL-E 3 request:', { size });

  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'dall-e-3',
      prompt: prompt,
      n: 1,
      size: size,
      quality: 'standard', // 'standard' or 'hd'
      response_format: 'url', // Return URL instead of base64
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    console.error('DALL-E error:', error);
    throw new Error(`DALL-E failed: ${error.error?.message || response.status}`);
  }

  const result = await response.json();

  if (!result.data || result.data.length === 0) {
    throw new Error('No image generated by DALL-E');
  }

  const imageUrl = result.data[0].url;
  console.log('Image generated successfully with DALL-E 3');

  return imageUrl;
}

/**
 * Generate image using specified provider
 */
async function generateImage(
  prompt: string,
  provider: 'stability' | 'dalle',
  style?: string,
  aspectRatio?: string
): Promise<{ imageUrl: string; provider: string }> {
  console.log(`Generating image with ${provider}...`);
  console.log('Prompt:', prompt);

  let imageUrl: string;

  if (provider === 'stability') {
    imageUrl = await generateWithStability(prompt, style, aspectRatio);
  } else if (provider === 'dalle') {
    imageUrl = await generateWithDalle(prompt, aspectRatio);
  } else {
    throw new Error(`Unknown provider: ${provider}`);
  }

  return {
    imageUrl,
    provider,
  };
}

serve(async (req: Request) => {
  const origin = req.headers.get('origin');

  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return handleCorsPreflightRequest(req);
  }

  // Only accept POST requests
  if (req.method !== 'POST') {
    return errorResponse('Method not allowed', 405, origin);
  }

  try {
    console.log('=== Generate Featured Image Request ===');

    // Parse request body
    const body = await req.json();
    const {
      prompt,
      provider = 'stability',
      style = 'photographic',
      aspect_ratio = '16:9',
    } = body;

    // Validate required fields
    if (!prompt) {
      return errorResponse('Missing prompt', 400, origin);
    }

    if (provider !== 'stability' && provider !== 'dalle') {
      return errorResponse('Invalid provider. Must be "stability" or "dalle"', 400, origin);
    }

    console.log('Provider:', provider);
    console.log('Style:', style);
    console.log('Aspect Ratio:', aspect_ratio);

    // Check if API keys are configured
    if (provider === 'stability' && !STABILITY_API_KEY) {
      return errorResponse(
        'Stability AI is not configured. Please set STABILITY_API_KEY environment variable.',
        500,
        origin
      );
    }

    if (provider === 'dalle' && !OPENAI_API_KEY) {
      return errorResponse(
        'OpenAI is not configured. Please set OPENAI_API_KEY environment variable.',
        500,
        origin
      );
    }

    // Generate the image
    let result;
    try {
      result = await generateImage(prompt, provider, style, aspect_ratio);
    } catch (error) {
      console.error('Image generation failed:', error);
      const errorMsg = error instanceof Error ? error.message : 'Failed to generate image';
      return errorResponse(errorMsg, 500, origin);
    }

    console.log('Image generation completed successfully!');

    // Return success response
    return jsonResponse(
      {
        success: true,
        image_url: result.imageUrl,
        provider: result.provider,
        prompt: prompt,
        aspect_ratio: aspect_ratio,
      },
      200,
      origin
    );
  } catch (error) {
    console.error('Generate featured image error:', error);
    const errorMsg = error instanceof Error ? error.message : 'Internal server error';
    return errorResponse(errorMsg, 500, origin);
  }
});
